### ISSUE TITLE
File `humdrumR.Rproj` referenced in "Getting Started" but not present

### ISSUE THREAD

**Issue by johentsch** [Computational-Cognitive-Musicology-Lab/humdrumR#15]
Currently, https://computational-cognitive-musicology-lab.github.io/humdrumR/articles/GettingStarted.html states:

> If you downloaded RStudio, you can use the “Open Project” option and select the file humdrumR.Rproj from the repository.

Currently, I fail to find any `.Rproj` file throughout the repository. Am I looking in the wrong place?

**Comment by natsguitar** [comment]
Ah, we realized that cloning the `.Rproj` file on different machines was causing weird problems (probably because people are on different operating systems or using different versions of Rstudio), so we removed the `.Rproj` file from the github repo. 

I've updated the Getting Started guide with instructions on how to create a humdrumR RStudio project on your machine...this means _your_ RStudio session will create its own `.Rproj` file. This seems to me the right way to do this.
